# Generated by Django 4.1.7 on 2023-03-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_num', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('bezel', models.CharField(max_length=50)),
                ('case_size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('production_year', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('box_and_papers', models.BooleanField()),
                ('seller_location', models.CharField(max_length=100)),
            ],
        ),
    ]
