# Generated by Django 4.1.7 on 2023-03-05 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='date_scrapped',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
